### ISSUE TITLE
Julia version requirement

### ISSUE THREAD

**Issue by GregPlowman** [cormullion/Luxor.jl#5]
Docs say `Luxor currently runs on Julia version 0.5, using Cairo.jl and Colors.jl.`
Does this mean that it requires 0.5 as a minimum version?
Or does it work with 0.4 and 0.5?

Seems to install on 0.4
REQUIRE has 0.4

Perhaps docs could be clarified.

**Comment by cormullion** [comment]
It probably runs OK on 0.4 (Travis says it's OK too on Unix, but I can't test it on Windows so I'm not too sure...

**Comment by cormullion** [comment]
Hopefully slightly clearer in https://github.com/cormullion/Luxor.jl/commit/22d83c637a93f0991a50bdf5656f5862a3d9f22e.
