### ISSUE TITLE
Install error `stars.png (Permission denied)`

### ISSUE THREAD

**Issue by GregPlowman** [cormullion/Luxor.jl#6]
Windows 7, Julia 0.4.5:
```
julia> Pkg.add("Luxor")
INFO: Cloning cache of Luxor from https://github.com/cormullion/Luxor.jl.git
INFO: Installing Luxor v0.2.0
error: unable to create file docs/figures/stars.png (Permission denied)
```
Other files seem to get copied into `.julia\v0.4\Luxor\docs\figures` directory OK.

**Comment by cormullion** [comment]
Weird, the file seems OK here on github.com...

**Comment by GregPlowman** [comment]
OK I reinstalled Luxor and everything seems good. (No error this time and `stars.png` is in `figures` directory).
I did `Pkg.rm("Luxor")` and completely removed `Luxor` directory from `.julia\v0.4` before reinstalling.
Problem must have been at my end, so closing this.

**Comment by cormullion** [comment]
Thanks @GregPlowman. I like to blame cosmic rays for cases like this. :)
